import type { Metadata } from 'next';
import Link from 'next/link';
import LegalLayout from '../../components/LegalLayout';
import { SOCIAL_LINKS, TRUST_LINKS } from '../../lib/trust-links';

export const metadata: Metadata = {
  title: 'Ayuda · Kosmovia',
  description: 'Guía de la beta: comunidades, mensajes, fotos y PDF, wallet y PIN, Vaquita, Retos, Aprende Stellar y notificaciones de la app instalada.',
};

export default function AyudaPage() {
  return <LegalLayout title="Guía de uso y ayuda"
    intro="Kosmovia está en beta y usa Stellar testnet. Todos los saldos y pagos son de prueba, sin valor monetario. Sigue estos pasos para empezar."
    sections={[
      { id: 'entrar', title: '1. Entra a Kosmovia', content: <><p>Puedes <Link href="/bienvenida">volver a ver la bienvenida</Link> para repasar lo básico y encontrar los enlaces del proyecto.</p><ol><li>Abre <Link href="/login">Iniciar sesión</Link>.</li><li>Elige Google, email o conectar Freighter y completa los pasos de acceso.</li><li>Con Google o email, Pollar gestiona el acceso a tu wallet. Con Freighter, conectas tu wallet propia: revisa que use testnet y confirma lo que te solicite.</li><li>Crea tu perfil y elige un @usuario para que puedan encontrarte.</li></ol></> },
      { id: 'wallet', title: '2. Revisa tu wallet y saldo de prueba', content: <><p>Abre tu wallet para ver tu dirección pública, saldo de USDC de prueba y movimientos. Ese saldo sirve para probar funciones; no es dinero real.</p><p>Si no tienes saldo de prueba, no envíes fondos reales para intentar recargarlo. Consulta al equipo en el repositorio indicado al final.</p></> },
      { id: 'pin', title: '3. Crea tu PIN de pagos', content: <ol><li>Abre tu perfil y la configuración de seguridad.</li><li>Crea y confirma un PIN de seis dígitos que no compartas con nadie.</li><li>Úsalo para confirmar cada pago. El PIN confirma tu decisión dentro de Kosmovia; no sustituye la seguridad de tu wallet.</li></ol> },
      { id: 'enviar', title: '4. Envía USDC a un @usuario', content: <ol><li>Abre tu wallet y elige enviar.</li><li>Busca el @usuario y revisa que sea la persona correcta.</li><li>Ingresa el monto de USDC de prueba y revisa el resumen.</li><li>Confirma con tu PIN y, si usas Freighter, completa la confirmación que solicite tu wallet.</li><li>Consulta el comprobante. Una operación confirmada en Stellar no se puede deshacer.</li></ol> },
      { id: 'recibir', title: '5. Recibe con un enlace o QR', content: <ol><li>Abre la opción de recibir en tu wallet.</li><li>Copia tu enlace de recepción o muestra el código QR.</li><li>Compártelo con quien hará el envío y revisa tus movimientos cuando se confirme. Tu dirección de wallet es pública; tu PIN no se comparte.</li></ol> },
      { id: 'comunidad', title: '6. Crea una comunidad, canales y categorías', content: <ol><li>Elige crear una comunidad e indica su nombre y descripción.</li><li>Dentro de la comunidad, crea canales y categorías para organizar las conversaciones.</li><li>Usa canales privados cuando necesites limitar quién puede acceder.</li><li>Comparte la invitación y explica las reglas a quienes se unan.</li></ol> },
      { id: 'mensajes', title: '7. Conversa en canales o por mensaje directo', content: <><p>Abre un canal para conversar con sus miembros. Para hablar en privado, abre el perfil de una persona de tu comunidad y elige enviar un mensaje; encontrarás la conversación en Mensajes directos.</p><p>Enter envía y Shift + Enter agrega una línea. Puedes editar o borrar tus mensajes. Si falla un envío, revisa el aviso y reintenta desde el borrador.</p></> },
      { id: 'adjuntos', title: '8. Comparte fotos, imágenes y PDF', content: <ol><li>En un canal o mensaje directo, usa el botón de adjuntar para elegir archivos. En computadora también puedes pegar una imagen desde el portapapeles.</li><li>Se admiten PNG, JPEG, WebP, GIF y PDF: hasta cuatro archivos por mensaje y 5 MB por archivo.</li><li>Revisa las vistas previas y espera a que termine la subida. Puedes quitar un archivo antes de enviarlo.</li><li>Agrega un texto si quieres y toca Enviar. También puedes enviar solo los archivos.</li><li>Toca una imagen para ampliarla o un PDF para abrirlo o descargarlo. Los archivos siguen el acceso del canal o conversación donde se compartieron.</li></ol> },
      { id: 'cobros', title: '9. Usa #cobros y #verificacion-pagos', content: <ol><li>En tu comunidad, usa el canal <strong>#cobros</strong> para publicar un cobro con su concepto y monto de prueba.</li><li>Antes de pagar, revisa quién cobra, el monto y el destinatario; confirma con tu PIN.</li><li>Consulta los comprobantes en <strong>#verificacion-pagos</strong> y revisa el registro de Stellar para verificar la operación. El comprobante corresponde a testnet, sin dinero real.</li></ol> },
      { id: 'vaquita', title: '10. Abre Aplicaciones: Vaquita, Retos y Aprende Stellar', content: <><p>Desde una comunidad, abre <strong>Aplicaciones</strong>. Revisa los permisos de cada app antes de conectarla. Las solicitudes de pagos se confirman dentro de Kosmovia.</p><ul><li><strong>Vaquita:</strong> crea una colecta con nombre y objetivo, compártela en el chat y aporta USDC de prueba. Revisa el destinatario y el monto antes de confirmar con tu PIN.</li><li><strong>Retos:</strong> juega tres en raya o piedra, papel o tijera con miembros de tu comunidad y consulta tus puntos y el ranking.</li><li><strong>Aprende Stellar:</strong> completa lecciones cortas, cuestionarios y misiones para avanzar y conseguir insignias.</li></ul><p>Puedes revisar y revocar las conexiones de apps desde la configuración de tu perfil. Las apps no necesitan conocer tu PIN ni tus claves.</p></> },
      { id: 'notificaciones', title: '11. Activa notificaciones e instala la app', content: <ol><li>Abre tu perfil y la pestaña <strong>Notificaciones</strong>.</li><li>Toca <strong>Activar notificaciones</strong> y acepta el permiso del navegador para este dispositivo.</li><li>Elige si quieres recibir avisos de mensajes directos, menciones y pagos. Para avisar a alguien en un canal, menciona su @usuario.</li><li>En Chrome, usa <strong>Instalar app</strong> cuando aparezca, o busca la opción de instalación en el menú del navegador. En iPhone o iPad, abre el sitio en Safari, usa Compartir → Agregar a inicio y luego abre la app instalada para activar los avisos.</li><li>Las notificaciones pueden llegar en segundo plano y al tocarlas puedes volver a la conversación. Dependen de la conexión, del permiso del navegador y de los ajustes de batería y notificaciones del teléfono.</li><li>Si el permiso está bloqueado, habilítalo desde la configuración del sitio y vuelve a esta pestaña. Si aparece que el servicio no está disponible, consulta al equipo.</li></ol> },
      { id: 'seguridad', title: '12. Usa la beta con cuidado', content: <><p>No compartas tu PIN, claves privadas ni frase de recuperación. El equipo no necesita esos datos para ayudarte. Comprueba el destinatario y el resumen antes de aprobar un pago.</p><p>Comparte solo archivos y datos que quieras que vean los participantes de ese canal o conversación. Evita documentos sensibles durante la beta. Cierra sesión si usas un dispositivo compartido.</p><p>Antes de empezar, puedes leer {TRUST_LINKS.filter(link => link.href !== '/ayuda').map((link, index) => <ReactLink key={link.href} href={link.href} label={link.label} separator={index > 0} />)}.</p></> },
      { id: 'recuperar-pin', title: 'Si olvidas tu PIN', content: <ol><li>Abre la configuración de seguridad e inicia el restablecimiento del PIN.</li><li>El restablecimiento se activa a las 24 horas; no cambia el PIN de inmediato.</li><li>Durante la espera, puedes cancelar la solicitud con tu PIN actual si lo recuerdas.</li><li>Cuando se active, sigue las instrucciones para crear un nuevo PIN. Si no solicitaste el cambio, revisa el acceso a tu cuenta y contacta al equipo.</li></ol> },
      { id: 'preguntas', title: 'Preguntas frecuentes', content: <><h3>¿Es dinero real?</h3><p>No. La beta usa testnet y el USDC de prueba no tiene valor monetario.</p><h3>¿Cuánto cuesta?</h3><p>La beta es gratuita.</p><h3>¿Quién controla mi wallet?</h3><p>Con Google o email, Pollar gestiona el acceso. Con Freighter, tú controlas tu wallet propia. Kosmovia no guarda tus claves privadas ni frases semilla.</p><h3>¿Instalar la app activa las notificaciones?</h3><p>Debes activarlas y conceder permiso en cada dispositivo. Instalar la app por sí solo no concede ese permiso.</p></> },
      { id: 'contacto', title: 'Enlaces del proyecto y ayuda', content: <><p>Únete a la <a href="https://t.me/kosmovia_official" target="_blank" rel="noopener noreferrer">comunidad oficial de Telegram</a> para conversar y pedir orientación. Para reportar un fallo, usa el <a href="https://github.com/kosmovia/kosmovia" target="_blank" rel="noopener noreferrer">repositorio de GitHub</a> y describe qué pasó y cómo repetirlo.</p><p>Los reportes de GitHub y los mensajes de la comunidad son públicos: no compartas tu PIN, claves, mensajes privados ni datos sensibles. Si tu caso requiere información privada, pide al equipo un canal adecuado antes de enviarla.</p><ul>{SOCIAL_LINKS.map(link => <li key={link.href}><a href={link.href} target="_blank" rel="noopener noreferrer">{link.label} ↗</a></li>)}</ul></> },
    ]} />;
}

function ReactLink({ href, label, separator }: { href: string; label: string; separator: boolean }) {
  return <>{separator ? ' y ' : ''}<Link href={href}>{label}</Link></>;
}
