import type { Metadata } from 'next';
import LegalLayout from '../../components/LegalLayout';

export const metadata: Metadata = {
  title: 'Privacidad · Kosmovia',
  description: 'Qué datos usa Kosmovia durante la beta, qué información es pública en Stellar y cómo solicitar acceso, corrección o eliminación.',
};

export default function PrivacidadPage() {
  return <LegalLayout title="Política de Privacidad" draft
    intro="Aquí explicamos qué datos guardamos y para qué los usamos durante la beta en testnet. No hay dinero real, pero tus datos personales siguen siendo importantes."
    sections={[
      { id: 'datos', title: 'Qué datos guardamos', content: <ul><li>Tu perfil público: @usuario, nombre, avatar y biografía.</li><li>La dirección pública de tu wallet.</li><li>Mensajes de canales y mensajes directos. Los directos no son publicaciones públicas, pero se almacenan para prestar el servicio.</li><li>Registros de pagos, que también son públicos en Stellar.</li><li>Los aportes a vaquitas y los datos necesarios para mostrarlos.</li><li>Datos técnicos mínimos necesarios para operar, diagnosticar errores y proteger el servicio.</li></ul> },
      { id: 'secretos', title: 'Qué no guardamos', content: <p>Kosmovia no guarda tus claves privadas ni tus frases semilla. No guardamos tu PIN en texto legible: solo su hash, una representación usada para comprobarlo. El PIN no es una barrera criptográfica ni protege por sí solo las claves de tu wallet. Con Google o email, la custodia de la wallet corresponde a Pollar.</p> },
      { id: 'uso', title: 'Para qué usamos los datos', content: <p>Usamos estos datos para identificar tu cuenta, mostrar tu perfil, entregar mensajes, gestionar comunidades, procesar y mostrar pagos de prueba y aportes, atender solicitudes y prevenir abusos. Los datos técnicos permiten mantener el servicio y resolver fallas.</p> },
      { id: 'terceros', title: 'Servicios de terceros y datos públicos', content: <><ul><li><a href="https://pollar.xyz">Pollar</a> proporciona el acceso y crea y custodia la wallet cuando entras con Google o email; trata datos según su propia política.</li><li>Stellar es una red pública: direcciones y operaciones pueden consultarse fuera de Kosmovia. El @usuario no vuelve anónima tu actividad.</li><li>Los proveedores de hosting y base de datos procesan los datos necesarios para alojar el servicio. Usamos Postgres, alojado en servicios como Render o Supabase.</li></ul><p>Si usas Freighter, conectas tu wallet propia y confirmas las acciones que correspondan desde ella. Las mini-apps nunca reciben tu PIN ni tus claves privadas.</p></> },
      { id: 'conservacion', title: 'Cuánto tiempo conservamos los datos', content: <p>Conservamos los datos mientras tu cuenta esté activa y sean necesarios para prestar el servicio. Si solicitas borrar tu cuenta, eliminaremos o anonimizaremos los datos que podamos, salvo lo necesario para resolver incidentes o cumplir obligaciones aplicables. Las copias de respaldo pueden conservar datos hasta su siguiente renovación. Este borrador no fija todavía un plazo exacto de eliminación o de respaldo; debe definirse antes de mainnet. Los registros en Stellar no dependen de estos plazos.</p> },
      { id: 'derechos', title: 'Ver, corregir o borrar tus datos', content: <p>Puedes solicitar ver tus datos, corregirlos o borrar tu cuenta mediante el contacto al final de esta página. Necesitaremos comprobar que la solicitud corresponde a tu cuenta. Borrar la cuenta no borra ni revierte las operaciones de Stellar: esa información es pública y no se puede eliminar desde Kosmovia. Tampoco elimina copias que otras personas hayan conservado.</p> },
      { id: 'seguridad', title: 'Seguridad y tus cuidados', content: <p>Usamos controles de acceso y guardamos el PIN como hash para reducir riesgos, pero ningún sistema garantiza seguridad absoluta. Cuida tu cuenta de Google o email y tu wallet Freighter. No compartas tu PIN, claves privadas ni frase semilla. Si detectas un acceso sospechoso, contacta al equipo sin publicar datos sensibles.</p> },
      { id: 'menores', title: 'Personas menores de edad', content: <p>Kosmovia no está dirigido a menores de 18 años. Si detectas una cuenta de una persona menor de edad, contacta al equipo para que revise el caso y gestione la eliminación de los datos que corresponda.</p> },
      { id: 'cambios', title: 'Cambios a esta política', content: <p>Publicaremos cualquier actualización en esta página con su fecha. Si cambia de forma relevante el uso de tus datos, te avisaremos en la plataforma.</p> },
      { id: 'contacto', title: 'Contacto', content: <p>Para consultas o solicitudes sobre tus datos, contacta a kosmovia (por ahora en nuestro repositorio de GitHub: <a href="https://github.com/kosmovia/kosmovia">github.com/kosmovia/kosmovia</a>). GitHub es público: no incluyas mensajes privados, tu PIN ni otros datos sensibles; pide al equipo un medio adecuado para continuar la solicitud.</p> },
    ]} />;
}
