import type { Metadata } from 'next';
import LegalLayout from '../../components/LegalLayout';

export const metadata: Metadata = {
  title: 'Privacidad · Kosmovia',
  description: 'Qué datos usa Kosmovia durante la beta, qué información es pública en Stellar y cómo solicitar acceso, corrección o eliminación.',
};

export default function PrivacidadPage() {
  return <LegalLayout title="Política de Privacidad" draft
    intro="Aquí explicamos qué datos guardamos y para qué los usamos durante la beta en testnet. No hay dinero real, pero tus datos personales siguen siendo importantes."
    sections={[
      { id: 'datos', title: 'Qué datos guardamos', content: <ul><li>Tu perfil público: @usuario, nombre, avatar y biografía.</li><li>La dirección pública de tu wallet.</li><li>Mensajes de canales y mensajes directos. Los directos no son publicaciones públicas, pero se almacenan para prestar el servicio.</li><li>Imágenes y PDF que adjuntas, sus miniaturas cuando corresponda, nombre de archivo, tamaño, dimensiones y vínculo con el mensaje y la persona que lo subió.</li><li>Registros de pagos, que también son públicos en Stellar.</li><li>Los aportes a vaquitas, actividad de Retos y progreso de Aprende Stellar.</li><li>Las mini apps conectadas a tu cuenta y los permisos que autorizaste.</li><li>La suscripción de notificaciones de cada navegador: dirección técnica de entrega, claves de comunicación, información del navegador y tus preferencias de avisos.</li><li>Datos técnicos mínimos necesarios para operar, diagnosticar errores y proteger el servicio.</li></ul> },
      { id: 'secretos', title: 'Qué no guardamos', content: <p>Kosmovia no guarda tus claves privadas ni tus frases semilla. No guardamos tu PIN en texto legible: solo su hash, una representación usada para comprobarlo. El PIN no es una barrera criptográfica ni protege por sí solo las claves de tu wallet. Con Google o email, Pollar gestiona el acceso y la creación de la wallet según su servicio; sus condiciones explican las opciones de control y recuperación.</p> },
      { id: 'uso', title: 'Para qué usamos los datos', content: <p>Usamos estos datos para identificar tu cuenta, mostrar tu perfil, entregar mensajes y archivos, gestionar comunidades, procesar y mostrar pagos de prueba y aportes, guardar el progreso de las mini apps, enviar los avisos que activaste y prevenir abusos. Los datos técnicos permiten mantener el servicio y resolver fallas.</p> },
      { id: 'archivos', title: 'Cómo tratamos los archivos que compartes', content: <><p>Los mensajes y archivos se procesan en el servidor; no ofrecemos cifrado de extremo a extremo. El acceso a un adjunto depende del canal o conversación donde lo compartes. Antes de enviarlo, solo puede consultarlo quien lo subió.</p><p>Las imágenes se vuelven a codificar, se ajustan de tamaño y generan una miniatura. La versión guardada no conserva los metadatos originales de la imagen, como ubicación GPS o cámara; un GIF animado queda como imagen estática. Los PDF se guardan como los subes: revisa su contenido y metadatos antes de compartirlos.</p></> },
      { id: 'notificaciones', title: 'Notificaciones en cada dispositivo', content: <><p>Solo enviamos notificaciones push cuando activas el permiso y registras ese navegador. Sus datos de suscripción se usan para entregar avisos mediante el servicio de push del navegador. El aviso puede incluir una vista previa del mensaje o los datos del pago, visibles también en la pantalla de bloqueo según la configuración de tu teléfono.</p><p>En Configuración de Cuenta → Notificaciones puedes desactivarlas en ese dispositivo y elegir avisos de pagos, mensajes directos y menciones. Las preferencias de tipos de aviso se aplican a toda tu cuenta. Cerrar sesión desvincula las notificaciones de ese navegador, sin desactivar tus otros dispositivos.</p></> },
      { id: 'bienvenida', title: 'Recordatorio de bienvenida en tu navegador', content: <p>Usamos el almacenamiento local de este navegador para recordar si ya viste la bienvenida. La marca <code>kosmovia:trust-welcome:v1</code> no contiene datos personales ni se usa como consentimiento legal. Si borras los datos del sitio o usas otro navegador, la bienvenida puede aparecer nuevamente.</p> },
      { id: 'miniapps', title: 'Permisos de las mini apps', content: <p>Al conectar una mini app registramos la conexión y sus permisos. Según la app, puede acceder a tu perfil, publicar mensajes o solicitar una confirmación de pago a través de Kosmovia. No recibe tu PIN ni tus claves privadas. Puedes revocar el acceso en Configuración de Cuenta → Seguridad → Apps conectadas; esto no borra mensajes, aportes o progreso que ya se hayan guardado.</p> },
      { id: 'terceros', title: 'Servicios de terceros y datos públicos', content: <><ul><li><a href="https://pollar.xyz">Pollar</a> proporciona el acceso y la creación de la wallet cuando entras con Google o email; trata los datos que necesita según sus propias condiciones y política.</li><li>Stellar es una red pública: direcciones y operaciones pueden consultarse fuera de Kosmovia. El @usuario no vuelve anónima tu actividad.</li><li>Los proveedores de hosting y base de datos procesan los datos necesarios para alojar el servicio. La base Postgres guarda también los adjuntos y sus miniaturas. Los proveedores de infraestructura y el servicio de push del navegador intervienen en el alojamiento y entrega correspondientes.</li></ul><p>Si usas Freighter, conectas tu wallet propia y confirmas las acciones que correspondan desde ella. Las mini-apps nunca reciben tu PIN ni tus claves privadas.</p></> },
      { id: 'conservacion', title: 'Cuánto tiempo conservamos los datos', content: <p>Conservamos los datos mientras tu cuenta esté activa y sean necesarios para prestar el servicio. Si solicitas borrar tu cuenta, eliminaremos o anonimizaremos los datos que podamos, salvo lo necesario para resolver incidentes o cumplir obligaciones aplicables. Las copias de respaldo pueden conservar datos hasta su siguiente renovación. Este borrador no fija todavía un plazo exacto de eliminación o de respaldo; debe definirse antes de mainnet. Los registros en Stellar no dependen de estos plazos.</p> },
      { id: 'derechos', title: 'Ver, corregir o borrar tus datos', content: <p>Puedes solicitar ver tus datos, corregirlos o borrar tu cuenta mediante el contacto al final de esta página. Necesitaremos comprobar que la solicitud corresponde a tu cuenta. Borrar la cuenta no borra ni revierte las operaciones de Stellar: esa información es pública y no se puede eliminar desde Kosmovia. Tampoco elimina copias que otras personas hayan conservado.</p> },
      { id: 'seguridad', title: 'Seguridad y tus cuidados', content: <p>Usamos controles de acceso y guardamos el PIN como hash para reducir riesgos, pero ningún sistema garantiza seguridad absoluta. Cuida tu cuenta de Google o email y tu wallet Freighter. No compartas tu PIN, claves privadas ni frase semilla. Si detectas un acceso sospechoso, contacta al equipo sin publicar datos sensibles.</p> },
      { id: 'menores', title: 'Personas menores de edad', content: <p>Kosmovia no está dirigido a menores de 18 años. Si detectas una cuenta de una persona menor de edad, contacta al equipo para que revise el caso y gestione la eliminación de los datos que corresponda.</p> },
      { id: 'cambios', title: 'Cambios a esta política', content: <p>Publicaremos cualquier actualización en esta página con su fecha. Si cambia de forma relevante el uso de tus datos, te avisaremos en la plataforma.</p> },
      { id: 'contacto', title: 'Contacto', content: <p>Para consultas generales, visita la <a href="https://t.me/kosmovia_official">comunidad oficial en Telegram</a>. <a href="https://github.com/kosmovia/kosmovia">GitHub</a> sirve para reportes públicos de fallas. No publiques mensajes privados, tu PIN, claves privadas ni datos personales en esos espacios. Para una solicitud sobre tu cuenta, pide al equipo un medio adecuado antes de compartir la información necesaria.</p> },
    ]} />;
}
